In [2]:
import numpy as np
STUDENT_NAME = "Angel Brisenio"
STUDENT_ID = 3695
np.random.seed(STUDENT_ID)
data = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)
print(f"{STUDENT_NAME}'s Array:", data)
mean_val = np.mean(data)
std_val = np.std(data)
print("Mean:", mean_val, "Std Dev:", std_val)

Angel Brisenio's Array: [139  20 140  95 107 144  92  47  64  79]
Mean: 92.7 Std Dev: 39.507087971653895


In [3]:
np.random.seed(STUDENT_ID)
matrix = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4))
print(f"{STUDENT_NAME}'s Matrix:\n", matrix)
row_sums = np.sum(matrix, axis=1)
col_sums = np.sum(matrix, axis=0)
print("Row sums:", row_sums)
print("Column sums:", col_sums)

Angel Brisenio's Matrix:
 [[11 39 20 20]
 [12 31 56 43]
 [20 56 16 28]]
Row sums: [ 90 142 120]
Column sums: [ 43 126  92  91]


In [4]:
np.random.seed(STUDENT_ID)
arr3d = np.random.randint(0, STUDENT_ID % 20 + 10, size=(3,3,3))
print(f"{STUDENT_NAME}'s 3D Array:\n", arr3d)
slice_mid = arr3d[:,1,:]
print("Slice[:,1,:]:\n", slice_mid)

Angel Brisenio's 3D Array:
 [[[10  6 19]
  [19 11 23]
  [10 19 23]]

 [[15 14  8]
  [14 10  9]
  [23 12  3]]

 [[19  9  6]
  [15 14  7]
  [ 8  3  0]]]
Slice[:,1,:]:
 [[19 11 23]
 [14 10  9]
 [15 14  7]]


In [5]:
np.random.seed(STUDENT_ID)
x = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)
filtered = x[(x>STUDENT_ID%50) & (x<STUDENT_ID%100)]
print(f"{STUDENT_NAME}'s Original:", x)
print("Filtered subset:", filtered)

Angel Brisenio's Original: [139  20 140  95 107 144  92  47  64  79]
Filtered subset: [92 47 64 79]


In [6]:
np.random.seed(STUDENT_ID)
A = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))
B = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))
print("Matrix A:\n", A)
print("Matrix B:\n", B)
product = A @ B
det_A = np.linalg.det(A)
print("A @ B:\n", product)
print("Determinant of A:", det_A)

Matrix A:
 [[11 39]
 [20 20]]
Matrix B:
 [[12 31]
 [56 43]]
A @ B:
 [[2316 2018]
 [1360 1480]]
Determinant of A: -559.9999999999999


In [7]:
angles = np.linspace(0, 2*np.pi, 8)
sine_vals = np.sin(angles)
cos_vals = np.cos(angles)
print(f"{STUDENT_NAME}'s Angles:", angles)
print("Sine:", sine_vals)
print("Cosine:", cos_vals)

Angel Brisenio's Angles: [0.         0.8975979  1.7951958  2.6927937  3.5903916  4.48798951
 5.38558741 6.28318531]
Sine: [ 0.00000000e+00  7.81831482e-01  9.74927912e-01  4.33883739e-01
 -4.33883739e-01 -9.74927912e-01 -7.81831482e-01 -2.44929360e-16]
Cosine: [ 1.          0.6234898  -0.22252093 -0.90096887 -0.90096887 -0.22252093
  0.6234898   1.        ]


In [8]:
np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(4,4))
arr[::2, ::2] = 0
print(f"{STUDENT_NAME}'s Modified 4x4 Array:\n", arr)

Angel Brisenio's Modified 4x4 Array:
 [[ 0 39  0 20]
 [12 31 56 43]
 [ 0 56  0 28]
 [61 47  9 64]]


In [9]:
np.random.seed(STUDENT_ID)
scores = np.random.randint(0, STUDENT_ID % 100 + 50, 10)
grades = np.where(scores>=STUDENT_ID%70,'Pass','Fail')
print(f"{STUDENT_NAME}'s Scores:", scores)
print("Grades:", grades)

Angel Brisenio's Scores: [138  19 139  94 106 143  91  46  63  78]
Grades: ['Pass' 'Fail' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Fail' 'Pass' 'Pass']


In [10]:
np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4))
flat_arr = arr.flatten()
transposed_arr = arr.T
print("Original array:\n", arr)
print("Flattened:", flat_arr)
print("Transposed:\n", transposed_arr)

Original array:
 [[11 39 20 20]
 [12 31 56 43]
 [20 56 16 28]]
Flattened: [11 39 20 20 12 31 56 43 20 56 16 28]
Transposed:
 [[11 12 20]
 [39 31 56]
 [20 56 16]
 [20 43 28]]


In [11]:
np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, (3,3))
mask = arr % 2 == 0
arr[mask] = -1
print("Array with conditional replacements:\n", arr)

Array with conditional replacements:
 [[11 39 -1]
 [-1 -1 31]
 [-1 43 -1]]


In [12]:
import pandas as pd
np.random.seed(STUDENT_ID)
df = pd.DataFrame({
 'Name': [STUDENT_NAME]*5,
 'Score': np.random.randint(STUDENT_ID%50,
STUDENT_ID%100+50,5),
 'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10,5)
})
print(df)

             Name  Score  YearsCodePro
0  Angel Brisenio     55            23
1  Angel Brisenio     83            10
2  Angel Brisenio     64            19
3  Angel Brisenio    128            23
4  Angel Brisenio     56            15


In [13]:
np.random.seed(STUDENT_ID)
df = pd.DataFrame({
'EdLevel': ['Bachelor','Master','PhD','Bachelor','Master'],
# Corrected to use a functional salary range, e.g., 40000 to 150000
'ConvertedComp': np.random.randint(40000, 150000, 5)
})
avg_salary = df.groupby('EdLevel')['ConvertedComp'].mean()
print(avg_salary)

EdLevel
Bachelor    129738.5
Master      104514.0
PhD          87123.0
Name: ConvertedComp, dtype: float64


In [14]:
np.random.seed(STUDENT_ID)
df = pd.DataFrame({
 'Country': ['Philippines','USA','UK','Canada','Germany'],
 'ConvertedComp': np.random.randint(40000, 150000, 5)
})
top5 = df.sort_values(by='ConvertedComp', ascending=False)
print(top5)

       Country  ConvertedComp
3       Canada         143307
1          USA         140006
0  Philippines         116170
2           UK          87123
4      Germany          69022


In [15]:
np.random.seed(STUDENT_ID)
df = pd.DataFrame({
 'Name':[STUDENT_NAME]*5,
 'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10,5)
})
high_exp = df[df['YearsCodePro']>STUDENT_ID%10]
print(high_exp)

             Name  YearsCodePro
0  Angel Brisenio            10
1  Angel Brisenio             6
2  Angel Brisenio            19
3  Angel Brisenio            19
4  Angel Brisenio            11


In [16]:
np.random.seed(STUDENT_ID)
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000,
150000, 5)})
bins = [0, 50000, 100000, 150000, 200000]
labels = ['0-50k', '50-100k', '100-150k', '>150k']
df['Bracket'] = pd.cut(df['ConvertedComp'], bins=bins, labels=labels)
print(df)

   ConvertedComp   Bracket
0         116170  100-150k
1         140006  100-150k
2          87123   50-100k
3         143307  100-150k
4          69022   50-100k


In [17]:
np.random.seed(STUDENT_ID)
# Original Code Issue:
# np.random.randint(STUDENT_ID%40000, STUDENT_ID%150000, 5)
# -> np.random.randint(12345, 12345, 5) which is a zero-length range.
# Corrected Code: Using a functional salary range (40000 to 150000)
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000,
150000, 5)})
df['LogComp'] = np.log(df['ConvertedComp'])
print(df)

   ConvertedComp    LogComp
0         116170  11.662810
1         140006  11.849441
2          87123  11.375076
3         143307  11.872744
4          69022  11.142181


In [18]:
np.random.seed(STUDENT_ID)
df = pd.DataFrame({
'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10, 5),
'ConvertedComp': np.random.randint(40000, 150000, 5)
})
corr_matrix = df.corr()
print(corr_matrix)

               YearsCodePro  ConvertedComp
YearsCodePro       1.000000       0.536808
ConvertedComp      0.536808       1.000000


In [19]:
np.random.seed(STUDENT_ID)
df = pd.DataFrame({
'EdLevel':['Bachelor','Master','PhD','Bachelor','Master'],
'ConvertedComp': np.random.randint(40000, 150000, 5)
})
# Calculate mean, median, and standard deviation for each 'EdLevel'
summary = df.groupby('EdLevel')['ConvertedComp'].agg(['mean','median','std']).reset_index()
print(summary)


    EdLevel      mean    median           std
0  Bachelor  129738.5  129738.5  19188.756721
1    Master  104514.0  104514.0  50193.267756
2       PhD   87123.0   87123.0           NaN


In [20]:
np.random.seed(STUDENT_ID)
# Generate salaries: [100727, 136195, 130612, 100727, 95233]
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000,
150000, 5)})
threshold = 110000
# Create the 'HighPay' column using np.where()
df['HighPay'] = np.where(df['ConvertedComp'] > threshold, 'Yes', 'No')
print(df)

   ConvertedComp HighPay
0         116170     Yes
1         140006     Yes
2          87123      No
3         143307     Yes
4          69022      No


In [21]:
np.random.seed(STUDENT_ID)
df = pd.DataFrame({
'Country': ['Philippines','USA','UK','Canada','Germany'],
'ConvertedComp': np.random.randint(40000, 150000, 5)
})
# Group by 'Country' and calculate the mean and max 'ConvertedComp'
top_countries = df.groupby('Country')['ConvertedComp'].agg(['mean','max'])
print(top_countries)

                 mean     max
Country                      
Canada       143307.0  143307
Germany       69022.0   69022
Philippines  116170.0  116170
UK            87123.0   87123
USA          140006.0  140006
