In [2]:
import numpy as np
STUDENT_NAME = "Sandrex J. Dala"
STUDENT_ID = 3410
np.random.seed(STUDENT_ID)
data = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)
print(f"{STUDENT_NAME}'s Array:", data)
mean_val = np.mean(data)
std_val = np.std(data)
print("Mean:", mean_val, "Std Dev:", std_val)

Sandrex J. Dala's Array: [47 49 45 37 28 11  6 13 23  6]
Mean: 26.5 Std Dev: 16.29877295995008


In [3]:
np.random.seed(STUDENT_ID)
matrix = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4))
print(f"{STUDENT_NAME}'s Matrix:\n", matrix)
row_sums = np.sum(matrix, axis=1)
col_sums = np.sum(matrix, axis=0)
print("Row sums:", row_sums)
print("Column sums:", col_sums)

Sandrex J. Dala's Matrix:
 [[15 17 13 29]
 [ 5 28 11  6]
 [13 23  6 16]]
Row sums: [74 50 58]
Column sums: [33 68 30 51]


In [4]:
np.random.seed(STUDENT_ID)
arr3d = np.random.randint(0, STUDENT_ID % 20 + 10, size=(3,3,3))
print(f"{STUDENT_NAME}'s 3D Array:\n", arr3d)
slice_mid = arr3d[:,1,:]
print("Slice[:,1,:]:\n", slice_mid)

Sandrex J. Dala's 3D Array:
 [[[14 16 12]
  [ 4 10  5]
  [12  5 15]]

 [[15  2  7]
  [12 14 11]
  [14 18 10]]

 [[19 15 15]
  [ 3 13 12]
  [13  5 15]]]
Slice[:,1,:]:
 [[ 4 10  5]
 [12 14 11]
 [ 3 13 12]]


In [5]:
np.random.seed(STUDENT_ID)
x = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)
filtered = x[(x>STUDENT_ID%50) & (x<STUDENT_ID%100)]
print(f"{STUDENT_NAME}'s Original:", x)
print("Filtered subset:", filtered)

Sandrex J. Dala's Original: [47 49 45 37 28 11  6 13 23  6]
Filtered subset: []


In [6]:
np.random.seed(STUDENT_ID)
A = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))
B = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))
print("Matrix A:\n", A)
print("Matrix B:\n", B)
product = A @ B
det_A = np.linalg.det(A)
print("A @ B:\n", product)
print("Determinant of A:", det_A)

Matrix A:
 [[15 17]
 [13 29]]
Matrix B:
 [[ 5 28]
 [11  6]]
A @ B:
 [[262 522]
 [384 538]]
Determinant of A: 214.0000000000001


In [7]:
angles = np.linspace(0, 2*np.pi, 8)
sine_vals = np.sin(angles)
cos_vals = np.cos(angles)
print(f"{STUDENT_NAME}'s Angles:", angles)
print("Sine:", sine_vals)
print("Cosine:", cos_vals)

Sandrex J. Dala's Angles: [0.         0.8975979  1.7951958  2.6927937  3.5903916  4.48798951
 5.38558741 6.28318531]
Sine: [ 0.00000000e+00  7.81831482e-01  9.74927912e-01  4.33883739e-01
 -4.33883739e-01 -9.74927912e-01 -7.81831482e-01 -2.44929360e-16]
Cosine: [ 1.          0.6234898  -0.22252093 -0.90096887 -0.90096887 -0.22252093
  0.6234898   1.        ]


In [8]:
np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(4,4))
arr[::2, ::2] = 0
print(f"{STUDENT_NAME}'s Modified 4x4 Array:\n", arr)

Sandrex J. Dala's Modified 4x4 Array:
 [[ 0 17  0 29]
 [ 5 28 11  6]
 [ 0 23  0 16]
 [26 16 22  3]]


In [9]:
np.random.seed(STUDENT_ID)
scores = np.random.randint(0, STUDENT_ID % 100 + 50, 10)
grades = np.where(scores>=STUDENT_ID%70,'Pass','Fail')
print(f"{STUDENT_NAME}'s Scores:", scores)
print("Grades:", grades)

Sandrex J. Dala's Scores: [46 48 44 36 27 10  5 12 22  5]
Grades: ['Fail' 'Fail' 'Fail' 'Fail' 'Fail' 'Fail' 'Fail' 'Fail' 'Fail' 'Fail']


In [10]:
np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4))
flat_arr = arr.flatten()
transposed_arr = arr.T
print("Original array:\n", arr)
print("Flattened:", flat_arr)
print("Transposed:\n", transposed_arr)

Original array:
 [[15 17 13 29]
 [ 5 28 11  6]
 [13 23  6 16]]
Flattened: [15 17 13 29  5 28 11  6 13 23  6 16]
Transposed:
 [[15  5 13]
 [17 28 23]
 [13 11  6]
 [29  6 16]]


In [11]:
np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, (3,3))
mask = arr % 2 == 0
arr[mask] = -1
print("Array with conditional replacements:\n", arr)

Array with conditional replacements:
 [[15 17 13]
 [29  5 -1]
 [11 -1 13]]


In [12]:
import pandas as pd
np.random.seed(STUDENT_ID)
df = pd.DataFrame({
 'Name': [STUDENT_NAME]*5,
 'Score': np.random.randint(STUDENT_ID%50,
STUDENT_ID%100+50,5),
 'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10,5)
})
print(df)

              Name  Score  YearsCodePro
0  Sandrex J. Dala     56            10
1  Sandrex J. Dala     58             5
2  Sandrex J. Dala     54            12
3  Sandrex J. Dala     46             5
4  Sandrex J. Dala     37            15


In [13]:
np.random.seed(STUDENT_ID)
df = pd.DataFrame({
'EdLevel': ['Bachelor','Master','PhD','Bachelor','Master'],
# Corrected to use a functional salary range, e.g., 40000 to 150000
'ConvertedComp': np.random.randint(40000, 150000, 5)
})
avg_salary = df.groupby('EdLevel')['ConvertedComp'].mean()
print(avg_salary)

EdLevel
Bachelor    101877.0
Master      109431.5
PhD          98156.0
Name: ConvertedComp, dtype: float64


In [14]:
np.random.seed(STUDENT_ID)
df = pd.DataFrame({
 'Country': ['Philippines','USA','UK','Canada','Germany'],
 'ConvertedComp': np.random.randint(40000, 150000, 5)
})
top5 = df.sort_values(by='ConvertedComp', ascending=False)
print(top5)

       Country  ConvertedComp
4      Germany         140287
3       Canada         102844
0  Philippines         100910
2           UK          98156
1          USA          78576


In [15]:
np.random.seed(STUDENT_ID)
df = pd.DataFrame({
 'Name':[STUDENT_NAME]*5,
 'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10,5)
})
high_exp = df[df['YearsCodePro']>STUDENT_ID%10]
print(high_exp)

              Name  YearsCodePro
0  Sandrex J. Dala            14
1  Sandrex J. Dala            16
2  Sandrex J. Dala            12
3  Sandrex J. Dala             4
4  Sandrex J. Dala            10


In [16]:
np.random.seed(STUDENT_ID)
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000,
150000, 5)})
bins = [0, 50000, 100000, 150000, 200000]
labels = ['0-50k', '50-100k', '100-150k', '>150k']
df['Bracket'] = pd.cut(df['ConvertedComp'], bins=bins, labels=labels)
print(df)

   ConvertedComp   Bracket
0         100910  100-150k
1          78576   50-100k
2          98156   50-100k
3         102844  100-150k
4         140287  100-150k


In [17]:
np.random.seed(STUDENT_ID)
# Original Code Issue:
# np.random.randint(STUDENT_ID%40000, STUDENT_ID%150000, 5)
# -> np.random.randint(12345, 12345, 5) which is a zero-length range.
# Corrected Code: Using a functional salary range (40000 to 150000)
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000,
150000, 5)})
df['LogComp'] = np.log(df['ConvertedComp'])
print(df)

   ConvertedComp    LogComp
0         100910  11.521984
1          78576  11.271822
2          98156  11.494313
3         102844  11.540969
4         140287  11.851446


In [18]:
np.random.seed(STUDENT_ID)
df = pd.DataFrame({
'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10, 5),
'ConvertedComp': np.random.randint(40000, 150000, 5)
})
corr_matrix = df.corr()
print(corr_matrix)

               YearsCodePro  ConvertedComp
YearsCodePro       1.000000      -0.238571
ConvertedComp     -0.238571       1.000000


In [19]:
np.random.seed(STUDENT_ID)
df = pd.DataFrame({
'EdLevel':['Bachelor','Master','PhD','Bachelor','Master'],
'ConvertedComp': np.random.randint(40000, 150000, 5)
})
# Calculate mean, median, and standard deviation for each 'EdLevel'
summary = df.groupby('EdLevel')['ConvertedComp'].agg(['mean','median','std']).reset_index()
print(summary)


    EdLevel      mean    median           std
0  Bachelor  101877.0  101877.0   1367.544515
1    Master  109431.5  109431.5  43636.266574
2       PhD   98156.0   98156.0           NaN


In [20]:
np.random.seed(STUDENT_ID)
# Generate salaries: [100727, 136195, 130612, 100727, 95233]
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000,
150000, 5)})
threshold = 110000
# Create the 'HighPay' column using np.where()
df['HighPay'] = np.where(df['ConvertedComp'] > threshold, 'Yes', 'No')
print(df)

   ConvertedComp HighPay
0         100910      No
1          78576      No
2          98156      No
3         102844      No
4         140287     Yes


In [21]:
np.random.seed(STUDENT_ID)
df = pd.DataFrame({
'Country': ['Philippines','USA','UK','Canada','Germany'],
'ConvertedComp': np.random.randint(40000, 150000, 5)
})
# Group by 'Country' and calculate the mean and max 'ConvertedComp'
top_countries = df.groupby('Country')['ConvertedComp'].agg(['mean','max'])
print(top_countries)

                 mean     max
Country                      
Canada       102844.0  102844
Germany      140287.0  140287
Philippines  100910.0  100910
UK            98156.0   98156
USA           78576.0   78576
